spring.application.name=Course Registration System

spring.datasource.url=jdbc:mysql://localhost:3306/course_reg_sys
spring.datasource.username=root
spring.datasource.password=Jahir14@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true